'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.'''

def evenFiboSum(n):
    a,b = 1,2
    sum = 0
    while a<=n:
        if a % 2 == 0:
            sum = sum+a
        a,b = b,a+b    
    return sum        
            
            
n = int(input("Enter a Number:-"))
print("Sum of Even Fibonacci:-",evenFiboSum(n))
            